apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "true"
    containerImage: registry.stage.redhat.io/rhpam-7/rhpam-rhel8-operator:7.12.1
    description: Deploys and manages Red Hat Process Automation Manager and Red Hat
      Decision Manager environments.
    operators.openshift.io/infrastructure-features: '["Disconnected"]'
    repository: https://github.com/kiegroup/kie-cloud-operator
    support: Red Hat
    tectonic-visibility: ocs
  name: businessautomation-operator.0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KieApp is the Schema for the kieapps API
      displayName: Kie App
      kind: KieApp
      name: kieapps.app.kiegroup.org
      version: v2
  description: Deploys and manages Red Hat Process Automation Manager environments.
  displayName: Business Automation Operator
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MjEuMTUgNzIxLjE1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2RkMzkyNjt9LmNscy0ye2ZpbGw6I2NjMzQyNzt9LmNscy0ze2ZpbGw6I2ZmZjt9LmNscy00e2ZpbGw6I2U1ZTVlNDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlByb2R1Y3RfSWNvbi1SZWRfSGF0LUF1dG9tYXRpb24tUkdCPC90aXRsZT48Y2lyY2xlIGNsYXNzPSJjbHMtMSIgY3g9IjM2MC41NyIgY3k9IjM2MC41NyIgcj0iMzU4LjU4Ii8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNjEzLjc4LDEwNy4wOSwxMDYuNzIsNjE0LjE2YzE0MC4xNCwxMzguNjIsMzY2LjExLDEzOC4xNiw1MDUuNjctMS40Uzc1Mi40LDI0Ny4yNCw2MTMuNzgsMTA3LjA5WiIvPjxwb2x5Z29uIGNsYXNzPSJjbHMtMyIgcG9pbnRzPSIzNzguOTcgMzI3LjQ4IDQ2MS43NyAxNTkuNTcgMjU5LjY3IDE1OS40OSAyNTkuNjcgNDEzLjEgMzA2Ljk3IDQxMy43OCAzOTMuMjcgMzI3LjQ3IDM3OC45NyAzMjcuNDgiLz48cG9seWdvbiBjbGFzcz0iY2xzLTQiIHBvaW50cz0iMzU5LjYgNTc4LjA2IDQ4Mi41NSAzMjcuNDUgMzkzLjI3IDMyNy40NyAzMDYuOTcgNDEzLjc4IDM1OS42IDQxNC41MiAzNTkuNiA1NzguMDYiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kieapp
  - pam
  - decision
  - kie
  - cloud
  - bpm
  - process
  - automation
  - operator
  labels:
    alm-owner-businessautomation: businessautomation-operator
    operated-by: businessautomation-operator.0.0.0
  links:
  - name: Product Page
    url: https://access.redhat.com/products/red-hat-process-automation-manager
  - name: Documentation
    url: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.12/#category-deploying-red-hat-process-automation-manager-on-openshift
  maintainers:
  - email: bsig-cloud@redhat.com
    name: Red Hat
  maturity: stable
  provider:
    name: Red Hat
    url: https://www.redhat.com
  replaces: businessautomation-operator.0.0.0
  selector:
    matchLabels:
      alm-owner-businessautomation: businessautomation-operator
      operated-by: businessautomation-operator.0.0.0
  version: 0.0.0
